// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_SaveEventLocations","status":true,"description":"v1.06 Enable specified maps to memorize the locations of\nevents when leaving and loading them upon reentering map.","parameters":{}},
{"name":"Galv_CollideSE","status":true,"description":"(v.1.0) Play a SE when player collides with impassable tile or event","parameters":{"Sound Effect":"dw1-bump,70,100","Repeat Wait":"16"}},
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"814","screenHeight":"720","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"DisableMouse","status":true,"description":"Disables mouse clicks.","parameters":{}},
{"name":"dw1","status":true,"description":"","parameters":{}}
];
